[{if $g_list}]
    [{$g_list}]
[{else}]
    [{if $smarty.post.step eq "2"}]
        [{include file="modules/export/step2.tpl"}]
    [{else}]
        [{include file="modules/export/step1.tpl"}]
    [{/if}]
[{/if}]