[{if $smarty.get.param eq $smarty.const.C__IMPORT__GET__FINISHED_IMPORTS}]
	[{include file="modules/import/import_done.tpl"}]
[{elseif $smarty.get.param eq $smarty.const.C__IMPORT__GET__IMPORT}]
	[{include file="modules/import/import_overview.tpl"}]
[{elseif $smarty.get.param eq $smarty.const.C__IMPORT__GET__SCRIPTS}]
	[{include file="modules/import/import_scripts.tpl"}]
[{elseif $smarty.get.param eq $smarty.const.C__IMPORT__GET__CABLING}]
	[{include file="modules/import/cabling_import.tpl"}]
[{/if}]